swagger: "2.0"
info:
  description: "This is the API for the Reactive Micro Service example"
  version: "1.0.0"
  title: "Reactive Microservices API"
  contact:
    url: "https://github.com/LearningByExample/reactive-ms-example"
host: "localhost:8080"
basePath: "/api"
tags:
- name: "hello"
  description: "Hello World"
schemes:
- "http"
paths:
  /hello:
    get:
      tags:
      - "hello"
      summary: "default get"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/HelloResult"
    post:
      tags:
      - "hello"
      summary: "post a name"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/HelloRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/HelloResult"
  /hello/{name}:
    get:
      tags:
      - "hello"
      summary: "get a name"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/HelloResult"
definitions:
  HelloRequest:
    type: "object"
    properties:
      name:
        type: "string"
  HelloResult:
    type: "object"
    properties:
      hello:
        type: "string"